module.exports = {
	botClientID: "985718921275510814",
	ownerIDs: ["638368326996983848"],
	embedColor: () => (Math.random() < 0.5 ? 0xff0000 : 0x0000ff), // Random red or blue
	embedfooterText: "Trike Returns I Guess",
	permisionerror: "You don't have the set permisions to do this. Get lost",
	jobs: [
		{
			name: "Retail Sales Associate",
			description: "You're unhappy and overworked, but at least you get a paycheck.",
			salary: 120,
			emoji: "🛍️",
			id: "retail_sales_associate",
			enabled: true,
		},
		{
			name: "Fast Food Worker",
			description: "Hot fries and cold cash, that's your life.",
			salary: 110,
			emoji: "🍔",
			id: "fast_food_worker",
			enabled: true,
		},
		{
			name: "Office Clerk",
			description: "Another day, another spreadsheet.",
			salary: 145,
			emoji: "📄",
			id: "office_clerk",
			enabled: true,
		},
		{
			name: "Delivery Driver",
			description: "Traffic jams and lights, that's your grind.",
			salary: 130,
			emoji: "🚚",
			id: "delivery_driver",
			enabled: true,
		},
		{
			name: "Warehouse Worker",
			description: "Heavy lifting and low pay, but you make it work.",
			salary: 125,
			emoji: "📦",
			id: "warehouse_worker",
			enabled: true,
		},
		{
			name: "Customer Service Representative",
			description: "You handle complaints like a pro, but it's draining.",
			salary: 115,
			emoji: "📞",
			id: "customer_service_representative",
			enabled: true,
		},
		{
			name: "Construction Laborer",
			description: "Hard hats and hard work, but the pay is decent.",
			salary: 150,
			emoji: "👷",
			id: "construction_laborer",
			enabled: true,
		},
		{
			name: "Janitor",
			description: "Cleaning up after others, but you take pride in your work.",
			salary: 100,
			emoji: "🧹",
			id: "janitor",
			enabled: true,
		}, // some goofy jobs
		{
			name: "Professional Napper",
			description: "You get paid to sleep, but it's not as easy as it sounds.",
			salary: 80,
			emoji: "😴",
			id: "professional_napper",
			enabled: true,
		},
		{
			name: "Pet Rock Trainer",
			description: "Training rocks to be the best they can be, one nap at a time.",
			salary: 90,
			emoji: "🪨",
			id: "pet_rock_trainer",
			enabled: true,
		},
		{
			name: "Cloud Counter",
			description: "Counting clouds all day, every day. It's a tough job.",
			salary: 70,
			emoji: "☁️",
			id: "cloud_counter",
			enabled: true,
		},
		{
			name: "Professional Line Stand-In",
			description: "You stand in lines so others don't have to. It's a calling.",
			salary: 85,
			emoji: "🕴️",
			id: "professional_line_stand_in",
			enabled: true,
		},
	],
};
